
class Solution(object):
    """
    @ Google

    Given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling
    string s and then add one more letter at a random position. Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
    """
    def findTheDifference_hashtable(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        adict = {}
        for c in s:
            if c not in adict:
                adict[c] = 1
            else:
                adict[c] += 1
        for c in t:
            if c not in adict or (c in adict and adict[c] == 0):
                return c
            else:
                adict[c] -= 1

    def findTheDifference_bitwise(self, s, t):
        st = s + t
        c = ord(st[0])
        for i in range(1, len(st)):
            c = c ^ ord(st[i])
        return chr(c)